### ISSUE TITLE
some styles of header definition (to add to a redirect) do not work as expected in netlify.toml (only when parsed by netlifyctl)

### ISSUE THREAD

**Issue by depadiernos** [netlify/netlifyctl#102]
**CONTEXT:**
Unable to use the following in a netlify.toml file:
```
[[redirects]]
  from = "/map"
  to = "https://maps.google.com"
  status = 200
  force = true
  headers = {X-From = "netlify_live", x-api-key= "LIVE API KEY"}
```

This causes the following error when running `netlifyctl deploy`

>"Near line 13 (last key parsed 'redirects.headers'): Expected value but found '{' instead."

**WORKAROUND:**

The following format, however, works:

```
[[redirects]]
  from = "/calculator/test"
  to = "https://futuregerald-requestbin.herokuapp.com/pzyoldpz"
  status = 200
  force = true
  [redirects.headers]
    X-From = "netlify_test"
    x-api-key= "TEST API KEY"
```

**Comment by fool** [comment]
Did you determine if a single header defined this way works @depadiernos ?  Is the bug limited to multiple?

**Comment by depadiernos** [comment]
The bug is not limited to multiple. Even with a single header, the deploy will fail. The following will fail also:

```
[[redirects]]
  from = "/map"
  to = "https://maps.google.com"
  status = 200
  force = true
  headers = {X-From = "netlify_live"}
```

**Comment by brycekahle** [comment]
The TOML parser we use only supports version [0.2.0](https://github.com/toml-lang/toml/blob/master/versions/en/toml-v0.2.0.md) of the TOML spec. Inline tables were added in 0.4.0.

**Comment by fool** [comment]
Thanks @brycekahle !  That also explains https://github.com/netlify/bitballoon/issues/1469 !

**Comment by brycekahle** [comment]
I was referencing the TOML parser we have in netlifyctl. I'm not sure what the origin uses. We should make sure they match though.
