### ISSUE TITLE
[GitLab] Push & Merge events not working properly.

### ISSUE THREAD

**Issue by skwidy** [netlify/netlifyctl#114]
Hello,

I've set up 3 statics angular 5 app with `init --manual`.
The first time, for each repo, everything went A-OK, I've even written a small medium post because it was not documented and I had to email the support (https://medium.com/captain-data-blog/how-to-deploy-any-git-repository-to-netlify-1a553b8e8e39).

However now whenever I push or merge, it just doesn't trigger the web hook.
When I try the web hook directly within GitLab, "push" events seems fine and I receive a 204, but I get a 422 when trying a "merge" event. 

When I push to master, it doesn't trigger the web hook and I need to `init --manual` again ... which is really annoying :) 

Any thoughts ?

**Comment by fool** [comment]
Hmm, haven't heard of that behavior before and it shouldn't be the norm, @skwidy , so it's worth debugging for sure!  Could you tell us:

1. are you using gitlab.com or self-hosted gitlab?
2. is there any "interesting" ownership/permission setup on your repo (a sub-group of a group that is owned by an organization)
3. what does the webhook request/response say when you examine the individual requests after choosing to edit the webhook in your repo settings?
4. which site or sites is it affecting?

If you get to the point where you'd be chopping out portions of your response for privacy, it is probably saner to debug this in a support ticket than in this thread.

**Comment by skwidy** [comment]
1. self-hosted on DigitalOcean

2. the ssh key generated during the init was setup in my profile settings and I'm the general admin/owner of the GitLab so I'd say there should be no problem on this side 

![capture d ecran 2018-05-23 a 21 42 34](https://user-images.githubusercontent.com/17913662/40447278-4f9df3ae-5ed2-11e8-97b9-accb07168d08.png)


3. You mean when I do this ? : 
![capture d ecran 2018-05-23 a 21 45 05](https://user-images.githubusercontent.com/17913662/40447400-b9b6c89c-5ed2-11e8-9154-736d5c883fa0.png)

I'll think about it yep :)

**Comment by skwidy** [comment]
It appears the SSH Keys were not added to the web hooks for some reason ... 
I closed the issued :)
