### ISSUE TITLE
netlifyctl deploy hangs during object upload 

### ISSUE THREAD

**Issue by jalalat** [netlify/netlifyctl#133]
1) Release version: v0.4.0
2) OS: Windows

I am facing the same issue as https://github.com/netlify/netlifyctl/issues/70

However the file size is 6MB.

**Comment by fool** [comment]
Could you please ping [our helpdesk](https://www.netlify.com/support) and mention this issue so we can work with you to debug?  I think this is likely specific to what you're trying to deploy and unless you'd like to share it in this thread (which is fine with me!) please get in touch there so we can see what you're working with and try to help you succeed in uploading :)

**Comment by mikirobles** [comment]
Any solution to this?
It's happening to me too

**Comment by rybit** [comment]
This project is not under active development at the time. Please look at https://github.com/netlify/cli for future development.
