### ISSUE TITLE
Install instructions for WSL

### ISSUE THREAD

**Issue by spences10** [netlify/netlifyctl#137]
You have kindly provided install instructions for a lot of platforms, thank you 🙏 

I know this is more a 'how to use Linux thing' rather than your responsibility but thought I'd ask here as you have so kindly given instructions on how to use for most other platforms.

How do you install the Linux binary on **Windows Subsystem Linux**?

**Comment by calavera** [comment]
Hi @spences10,

WSL behaves as any other Linux distro. Open your Ubuntu terminal, or the distro you have installed and follow the instructions for Linux in our README: https://github.com/netlify/netlifyctl#direct-binary-install-linux-mac-windows

**Comment by spences10** [comment]
Thanks for the reply @calavera 

I'm still not clear on what to do, when it says download directly it will download on the windows machine.

How do I extract it?

**Comment by spences10** [comment]
Ok, so here are the steps I used to install in WSL:

```sh
# navigate to download location of .tar.gz
sudo mv netlifyctl-linux-amd64-0.4.0.tar.gz /usr/local/bin/netlifyctl-linux-amd64-0.4.0.tar.gz
sudo tar zxf netlifyctl-linux-amd64-0.4.0.tar.gz
```

This worked and I can now use `netlifyctl -h` the thing is now I can't authenticate via WSL, it doesn't pop open the browser auth window.

**Comment by amanda62** [comment]
I'm having the same issue
