### ISSUE TITLE
Authentication browser window not opening for Windows Subsystem Linux (WSL)

### ISSUE THREAD

**Issue by spences10** [netlify/netlifyctl#138]
Hi,

I came across this issue when trying to install on WSL (#137) the CLI errors when trying to authenticate with `netlifyctl login`.

![image](https://user-images.githubusercontent.com/234708/43365090-fa3ce79a-931e-11e8-8cbd-1311407a05f7.png)

I can share the `netlifyctl-debug.log` contents if you can tell me what credentials to remove before posting, thanks.

**Comment by amanda62** [comment]
I'm having the same issue
