### ISSUE TITLE
How much longer is this cli supported?

### ISSUE THREAD

**Issue by zeusdeux** [netlify/netlifyctl#146]
Hi folks! We have a bunch of documentation that is based on this CLI and I was wondering how much longer this is going to be supported?

**Comment by rybit** [comment]
We are not going to be actively closing this out, but features and bugs will be slow to come on this project. https://github.com/netlify/cli will be getting active development.

**Comment by bcomnes** [comment]
Our go api client is also actively maintained https://github.com/netlify/open-api/tree/master/go
