### ISSUE TITLE
Deploy failed. 

### ISSUE THREAD

**Issue by kenlu89** [netlify/netlifyctl#150]
Was working fine before after adding favicon to the site. which is only 25kb image size. Here is the deploy failed message.

Tried 4th run with clear cache and run but still failed. Any suggestions?

![Screen Shot 2019-11-12 at 9 26 23 AM](https://user-images.githubusercontent.com/21323725/68679828-97b3d100-052e-11ea-9343-587cadc3bfea.png)

**Comment by rybit** [comment]
sorry to see that this happened. I'd recommend that you bring this up with support or via the forums.

This project is being sunset and take over by netlifycli
