### ISSUE TITLE
Ability to add comment to deploys

### ISSUE THREAD

**Issue by charlierudolph** [netlify/netlifyctl#28]
I am currently using this tool for manual deploys and would like to add a name/comment to manual deploys that would display on the deploys tab for an application. This is essentially a replacement for the sha / commit message that appears on the website for automated deploys.

I messaged support already and am aware that there is currently no API endpoint for this but they asked me to open an issue here so it can be tracked publicly.

**Comment by fool** [comment]
The mentioned API endpoint would need implemetation on the backend to enable this.  It would be awfully nifty to have this endpoint - not just for netlifyctl/netlify-cli but for drag and drop deploys too.

**Comment by charlierudolph** [comment]
Awesome. Thanks for the quick turnaround! Can you please let me know when a new release is available?

**Comment by fool** [comment]
It's available now: https://github.com/netlify/netlifyctl/releases/tag/v0.1.2
