### ISSUE TITLE
panic: interface conversion: interface {} is *models.Error, not *string

### ISSUE THREAD

**Issue by activatedgeek** [netlify/netlifyctl#39]
I am using the following command to deploy my site from the public folder - 

```
$ ./netlifyctl deploy -A $NETLIFY_ACCESS_TOKEN
```

Travis logs are available [here](https://travis-ci.org/activatedgeek/website/builds/255195653).

Can somebody help me fix this issue?

**Comment by rozhok** [comment]
Same user here. Need fix asap because we heavily rely from automated deployments.

**Comment by flavio-elder** [comment]
Hey same problem here. the
```
netlify deploy --site-id xxxxx-xxxxx-xxxxx-xxxx --path _site
```
seems to work for me in the meantime...

**Comment by fool** [comment]
We're working on determining a root cause before we publish a fix, folks.  Expected ETA in the next couple of hours.

**Comment by rybit** [comment]
ok so I think I have addressed the root cause. If you would like to test it that would be good. We will be cutting a release once we have confirmed for sure.

**Comment by rozhok** [comment]
How can I get the fix?

**Comment by rybit** [comment]
If you run a deploy with the master version of this you _should_ be good.

**Comment by rozhok** [comment]
I have following stuff in Dockerfile:
`RUN go get github.com/netlify/netlifyctl`
Will it pick up master? Not very familiar with go tools.

**Comment by rybit** [comment]
Yes that should do it

**Comment by rozhok** [comment]
Works for me.

**Comment by brycekahle** [comment]
v0.1.4 has been released and contains this fix.

**Comment by activatedgeek** [comment]
Thanks guys!
