### ISSUE TITLE
enable passing site ID or name via command line

### ISSUE THREAD

**Issue by fool** [netlify/netlifyctl#42]
Currently, the site ID must be read from the terminal (and thus entered in the toml file by netlifyctl to be used).  Would be great to be able to pass this via command line!

Make sure to update the help text if this option gets added please :)

**Comment by calavera** [comment]
any command in particular? the deploy command supports both now

**Comment by fool** [comment]
I'd say the deploy command just needs its --help text updated to complete this, then!

**Comment by malcolmr** [comment]
I don't think the deploy command works without a configuration file yet (or at least, I couldn't make it work): `netlifyctl deploy` appears to call `middleware.ChooseSiteConf()` first (which looks at the configuration, and prompts the user if there's ), and _then_ checks the --site-id flag.

**Comment by calavera** [comment]
we should probably switch the order to check the flag first

**Comment by malcolmr** [comment]
fwiw, looks like you could also call `configuration.SiteIdForCommand(cmd)` first, as `update` does (and prompt via `ChooseSiteConf()` if that failed), or extract the similar-but-not-identical `siteIdForCommand()` from the assets package into somewhere common.

**Comment by manico** [comment]
> we should probably switch the order to check the flag first

Any updates on this? Currently it is impossible to use as silent deploy. Example:

`netlifyctl deploy -s 78cf1c0c-6834-4cd8-9b9d-ee5765ef921e -b data/6ba7b810-9dad-11d1-80b4-00c04fd430c8`

**Comment by fool** [comment]
Not sure how soon we'll get this fixed up, y'all - PR's gladly accepted!
