### ISSUE TITLE
How to use Deploy Previews with this?

### ISSUE THREAD

**Issue by cheapsteak** [netlify/netlifyctl#43]
Can't use the web interface to setup Deploy Previews because the repo belongs to a Github Org that has restricted 3rd party app access, and the owners are all in the IT department and it would be a long wait to get them to approve

Tried netlify-cli but web hooks only manage to trigger production builds and not Deploy Previews (pushes and PRs on other branches trigger a production deployment build)

Tried this, but it also only deploys to the production url

It's cool that I can deploy without associating with a git repo, assumed it'd be possible to pass a flag to tell it this is a preview deploy, not implemented yet or did I miss it?

edit: looking at the [api docs](https://github.com/netlify/open-api/blob/master/swagger.yml#L362-L372), it looks like deploy previews aren't exposed via api?

**Comment by rybit** [comment]
So if I understand this correctly you're just doing deploys manually? Running `netlifyctl deploy` or the likes right? 

Deploy previews are enabled by default, but they require that you have integrated with our CI system. It uses git to trigger the previews for PRs and branches.

**Comment by cheapsteak** [comment]
Ah I see

Any way to integrate with your CI system without being an Github Org Owner?

I have admin access to the repo and can configure webhooks and deploy keys

**Comment by rybit** [comment]
If you write into support they can help you more.
