### ISSUE TITLE
Error: preprocessing deploy timed out

### ISSUE THREAD

**Issue by activatedgeek** [netlify/netlifyctl#44]
Please find the build logs [here](https://travis-ci.org/activatedgeek/website/builds/269445621#L1283).

**Comment by calavera** [comment]
We could definitely give more insight. I believe the problem was on the server side.

**Comment by fool** [comment]
Confirmed that this is a server side bug and not a netlifyctl bug.

You could get the same error by uploading a deploy via zipfile  or from git.

ping support@netlify.com if this happens to you and they'll try to help you work around it for your deploy.

**Comment by elskwid** [comment]
Hi @fool and @calavera, sorry to resurrect an old issue. We're having the same issue as the OP. I've sent a couple of emails to support@netlify.com with no response. Is there anything else we can do?

**Comment by fool** [comment]
Interesting, we've replied to all cases that you could have sent, @elskwid .  Perhaps your mail service is marking our responses as spam?  They'll come from our helpdesk but "from" an @netlify.com address.

Regardless, you can try using the `-p X` flag to set a longer timeout, I'd suggest `-p 600` to double the timeout.
