### ISSUE TITLE
Ensure feature parity with netlify-cli

### ISSUE THREAD

**Issue by verythorough** [netlify/netlifyctl#46]
It's difficult to recommend netlifyctl to users when it doesn't quite do everything netlify-cli does. If we want to be able to deprecate netlify-cli, let's get it on the roadmap to make netlifyctl do all that we need it to. 

I'd appreciate input from those in the know to start a list here of the features needed to make this complete.

In the meantime, I'll commit to writing up a doc to explain what can be done on each tool.

**Comment by verythorough** [comment]
Related docs requests from @fool:

> Need both a note in the GH/netlify-cli README.md pointing to this as a more stable CI-deployer
> and
> better docs in the GH/netlifyctl README.md about limitations (missing the site-modification stuff from netlify-cli) and the intended usage flow around setup and use (-C different.toml, -D, -A token)

**Comment by calavera** [comment]
> missing the site-modification stuff from netlify-cli
Unless there is something I missed, updating a site has been implemented for 9 months already:

https://github.com/netlify/netlifyctl/pull/16

Let's open specific issues with what's missing rather than opening another "let's talk about ..." issue.

/cc @fool

**Comment by fool** [comment]
wow, that was hard to discover, but now I see that it is all there, thanks David!  I've updated the README.md to make the 'netlifyctl site update' functionality more obvious.

I think the main missing functionality from my understanding now is around

`netlify init -m` that sets up an external repo for linking manually - @calavera is that secretly possible here in netlifyctl and I've missed it too?

**Comment by calavera** [comment]
that's not implemented, please open an issue to be explicit about it.

**Comment by fool** [comment]
new issue: https://github.com/netlify/netlifyctl/issues/47

...that is AFAIK all that is left to implement to complete this issue (#46).

So, I'll close this issue in favor of that one.
