### ISSUE TITLE
enable "manual" repository setup with netlifyctl

### ISSUE THREAD

**Issue by fool** [netlify/netlifyctl#47]
I'm looking for the same thing that `netlify init -m` does  using the old netlify-cli:

- reads .git/config for repo info for directory it is init'ing
- creates in our system a deploy key and webhook for a site and
- tells $customer the public_key and webhook address so they can put them in place manually in their repo settings

**Comment by verythorough** [comment]
When this is closed, please ping me or file a docs issue so we can update docs to recommend this over netlify-cli.

**Comment by fool** [comment]
@verythorough here's a ping - the CLI doc can be migrated in your copious spare time.  I put a note in it in your project dashboard to indicate it was unblocked too
