### ISSUE TITLE
deploy error: "too many open files"

### ISSUE THREAD

**Issue by fenollp** [netlify/netlifyctl#73]
```shell
$ cd mywebsite && netlifyctl deploy
CCounting objects  ✘    
open netlifyctl-debug.log: too many open files
$ echo $?
255
$ find .git -type f |wc -l
108
$ find . -type f |wc -l
34929
$ netlifyctl version
cb64d2d16fb15394bb7d24b9fdc6d535e3071560
```
I am trying to deploy a documentation website (small and numerous pages). It works using the `git push`-deploy though. I would prefer to rely on this client though...

This error seems to come from golang itself, [while accumulating](https://github.com/netlify/netlifyctl/blob/64badcbad373780a6dae8607c3d0c676507884d4/operations/deploy.go#L43) [file hashes](https://github.com/netlify/open-api/blob/03902f6dc39f38fad4e84a1c641a607549a8625f/go/porcelain/deploy.go#L480).

It seems something deadlocks while trying to read from my ssd? Should I do something like bumping my ulimit? I have 99% inodes free...
stacktrace: https://gist.github.com/fenollp/e2c63ba00e03246054563a02900f7361

Possible solutions:
* tar the website before sending (great for sending a lot of smallish files)
* add `--source` & `--target` flags to `deploy` that, in addition to `--base-directory`, allow uploading parts of a website. May also benefit people who want to update only part of their website.

Thanks

**Comment by fool** [comment]
This is a problem with your OS, not with netlifyctl.

On OSX, I worked around it like this:

```
sudo launchctl limit maxfiles 1000000
ulimit -n 1000000
netlifyctl deploy
```
...based on what I read here:  https://superuser.com/questions/302754/increase-the-maximum-number-of-open-file-descriptors-in-snow-leopard

**Comment by fenollp** [comment]
Yep `ulimit -n 100000` fixed it! (I'm on debian BTW).
At least a hint and at best a meaningful error would be great though. Either:
1. check `ulimit -n` against number of files in deploy path
1. or just print a warning when ulimit is low (~1024)

**Comment by calavera** [comment]
Actually, I think problem was related to this: https://github.com/netlify/open-api/issues/73

I updated the open-api dependency in master already. I'm going to release a new version soon.
