### ISSUE TITLE
return some indication of whether the old deployment was locked when a new production deploy is sent

### ISSUE THREAD

**Issue by fool** [netlify/netlifyctl#80]
This was a suggestion from a customer.

Scenario:  You use locked deploys in the UI to prevent autopublishing from git.  This works fine until you send a deploy via `netlifyctl deploy` which will publish the current deploy - and leave deploys UNLOCKED.

Suggestion:  before deploying, check for the current deploy being locked and output some sort of warning that you've now turned off locking and should revisit the site dashboard to re-lock deploys.

**Comment by calavera** [comment]
I would consider this a bug in Netlify's API. No deploys should unlock a locked deploy regardless the deploying method, either cli or netlify's CD.

**Comment by fool** [comment]
Support totally agrees but you said the opposite a few months ago :)  We'll file a bug and a doc update request instead!

**Comment by fool** [comment]
closing in favor of https://github.com/netlify/bitballoon/issues/1660
