### ISSUE TITLE
Deploying in windows creates paths with backslashes that don't work once deployed

### ISSUE THREAD

**Issue by futuregerald** [netlify/netlifyctl#84]
Deploying in windows creates paths with backslashes that don't work once deployed.

While version 0.3.2 was released to address this, the issue still persists:

    Deploy.find("5a8c9c467b6ee80bfd6616ed").files.map{|f| puts f.path }; nil
    /index.html
    /subtest\subbing.html
    => nil

And to confirm the version of the CTL being used:

    .\netlifyctl version
    Version: 0.3.2
    Git SHA: a1b86648871d4a5888a6a50e5e524cf650d5fa61

**Comment by futuregerald** [comment]
User to inform:

https://app.intercom.io/a/apps/q245f50x/inbox/inbox/1479299/conversations/14704303860

**Comment by calavera** [comment]
this was fixed in version 0.3.2: https://github.com/netlify/netlifyctl/releases/tag/v0.3.2

**Comment by ffpetrovic** [comment]
I still have the same issue with v0.3.2
