### ISSUE TITLE
Missing "Continue?" prompt when using init --manual  (Gitlab)

### ISSUE THREAD

**Issue by ackushiw** [netlify/netlifyctl#91]
Following the steps for `init --manual`

after reaching:
```
Configuring Continuous Deployment ... 🌎
Give this Netlify SSH public key access to your repository:

(SSH_KEY)
```

and copying and adding the SSH key to the gitlab repo:
GITLAB_PROJECT > Settings > Repository - **Deploy Keys**

the command line holds with
`Configuring Continuous Deployment ... 🌏` (with the globe animating)

**Comment by ackushiw** [comment]
Looking at the code https://github.com/netlify/netlifyctl/blob/80a78fe6bd839fb3419268ba70b9bbcc7c50c3f8/commands/init/manual.go#L20

I thought I'd try typing `y` then hitting enter
I can continue this way.

**Comment by fool** [comment]
Thanks for this report @ackushiw - wanted to confirm you did the right thing to get past it! Just found this myself too.

**Comment by fool** [comment]
cc @calavera or @rybit suspect this is an easy fix and tripped up another customer today - any chance we could get some eyes on it?
