### ISSUE TITLE
Installation fails on circleci/golang:1.9 docker image

### ISSUE THREAD

**Issue by emmenko** [netlify/netlifyctl#93]
Hey guys,

in our CircleCI build we use a `circleci/golang:1.9` docker image and install the `netlifyctl` CLI using `go get github.com/netlify/netlifyctl`.

Until a couple of days ago it was working fine but we now get this error:

```bash
$ go get github.com/netlify/netlifyctl
# github.com/netlify/netlifyctl/commands/deploy
/go/src/github.com/netlify/netlifyctl/commands/deploy/deploy.go:90:44: not enough arguments in call to client.WaitUntilDeployReady
	have ("github.com/netlify/netlifyctl/context".Context, *models.Deploy)
	want ("github.com/netlify/open-api/go/porcelain/context".Context, *models.Deploy, time.Duration)
```

Is there something wrong with the image itself or with the installation script?

Many thanks 🙏

**Comment by brycekahle** [comment]
This is a consequence of using `go get`, which uses the latest versions of dependencies. We use `glide` to help vendor our dependencies. Give this a try:
```
go get -d github.com/netlify/netlifyctl
cd /go/src/github.com/netlify/netlifyctl
make deps build
go install
```

Alternatively, we do provide pre-built [releases](https://github.com/netlify/netlifyctl/releases).

**Comment by emmenko** [comment]
Many thanks for your feedback! I'll give it a try then 👌
