### ISSUE TITLE
Add support for headers in configuration

### ISSUE THREAD

**Issue by tallclair** [netlify/netlifyctl#95]
Headers in `netlify.toml` are currently ignored by netlifyctl.

I assume this is a known issue, but wanted to file it to track the progress.

**Comment by fool** [comment]
Hi @tallclair ,

Could you show us a code snippet that fails?  There are some shortcomings (filed in https://github.com/netlify/netlifyctl/issues/102) in handling formats like:

`  headers = {name = "value" ...}`

but the general `[[headers]]` section and the variant specification of the above:

```
  [headers.values]
     name = "value"
     name2 =" ..."
```

should work.

**Comment by tallclair** [comment]
This was what I tried to deploy: https://github.com/tallclair/blog/blob/0577d7545955de77cf24a98fac5ca7ac1afbf746/netlify.toml
But when I realized it wasn't working I reverted to the `_headers` file (https://github.com/tallclair/blog/blob/2ffb1668f6075592b9b93d99fa1d947adf9752f3/static/_headers)

Apologies if this was a misconfiguration on my part - I looked at the configuration struct [here](https://github.com/netlify/netlifyctl/blob/286912f1956106de9a7a70bcb94d3b27dffab944/configuration/configuration.go#L24) and thought it wasn't parsing the headers section at all.
