### ISSUE TITLE
Internal support for netlifyctl at Netlify

### ISSUE THREAD

**Issue by chrstphrknwtn** [netlify/netlifyctl#96]
Does this project have much support at Netlify? Seems like the pace of adding basic features is pretty slow.

For example, having decent error messages #4 has been an issue for over 18 months.

Also, the [docs](https://www.netlify.com/docs/cli/) encourage the use of this newer, undocumented cli tool, but it seems pretty flakey. Seems better to just point to this tool as a beta.

**Comment by rybit** [comment]
This does have support from our team. It is a replacement for the older netlify-cli tool that is linked in the docs. We are going to be updating the docs soon to reference this tool

**Comment by chrstphrknwtn** [comment]
Updating the docs is one thing, having to the tool you're going to reference in a usable state seems to be another. Not trying to be overly critical, just saying that it _feels_ broken, and produces errors more than anything else.

**Comment by fool** [comment]
If you'd ping our support team or file issues, we'll be able to try to get those fixed, @chrstphrknwtn .  This tool works well for several hundred customers in production, including folks who deploy huge sites frequently.

The are only two meaningfully broken things we know about right now in this list, one of which is a display-only bug:

https://github.com/netlify/netlifyctl/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aopen+label%3Abug

We appreciate your help in reporting problems so we can get them fixed!
